-- Placeholder. No-op by design.
--
-- This Supabase project is shared by several restaurants, each isolated in its
-- own schema. `supabase_migrations.schema_migrations` therefore already records
-- versions applied from the other tenants' repos, and `supabase db push`
-- compares the local migrations directory against that shared ledger.
--
-- This version (later maintenance migration) lives in another tenant's repo and is already applied
-- on the remote. Without a local file of the same name the CLI reports
-- divergence and refuses to push.
--
-- Both real porca migrations sort BELOW the remote head, so the push must be
-- run with `--include-all`.
--
-- Do not put anything in this file. The real migration is not ours to own.
